services:

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 15432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080